# https://docs.docker.com/compose/

version: "3.4"

volumes:
  database:

networks:
  awari:

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - awari
    volumes:
      - database:/var/lib/mysql:rw

  api:
    build:
      #pasta externa de referencia onde está salvo o dockerfile
      context: .
      #Até qual estagio definido no dockerfile a aplicação deve ser executada
      target: build
    ports:
      - 4500:3000
    networks:
      - awari
    volumes:
      - .:/srv/app
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: root
      DATABASE_PASS: "123456"
      DATABASE_NAME: "blog"
